[package]
authors = ["Vadim Chugunov <vadimcn@gmail.com>"]
edition = "2018"
name = "adapter-protocol"
version = "0.1.0"

[dependencies]
schemafy = "0.5.2"
serde = { version = "1.0", features = ["derive"] }
#serde_derive = "1.0"
serde_json = "1.0"
